version: '3'

services:
  personapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  personfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

