version: '3'

services:
  personapi:
    image: personapi
    build:
      context: .
      dockerfile: PersonApi/Dockerfile

  personfrontend:
    image: personfrontend
    build:
      context: .
      dockerfile: PersonFrontEnd/Dockerfile

